### ISSUE TITLE
フォローボタンの実装

### ISSUE THREAD

**Issue by takecchi** [cuculus-dev/cuculus#340]
## Community Issue
https://github.com/cuculus-dev/.github/issues/20

## 概要
フォローボタンを押した時にフォローが出来ること

## Todo
- [x] フォロー状態をチェックする
  - [x] フォロー中だった場合は「フォロー中」の表示になる
    - [x] 「フォロー中」の状態で上にカーソルを乗せると文言が「フォロー解除」になる
      - [ ] 押下するとフォロー解除リクエストが送られる(出来れば確認ダイアログが欲しい)
  - [x] フォローしていない状態だった場合は「フォロー」ボタンが表示される
    - [x] 押下するとフォローが走る

**Comment by takecchi** [comment]
2024/03/11現在
リムーブ(フォロー解除)処理はまだバックエンド側で未実装なので、APIを叩いても実際には解除されない。

**Comment by takecchi** [comment]
## 関連API
フォロー状態チェック
https://api.develop.cuculus.jp/api#/users/getRelationShip

フォロー
https://api.develop.cuculus.jp/api#/users/createFollow

リムーブ
https://api.develop.cuculus.jp/api#/users/deleteFollow

**Comment by takecchi** [comment]
承認待ちも作らないと？別タスクで切り出す
